#### Operaciones de arrays

##### Producto por escalar
$$\begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n} 
 \end{pmatrix}·\lambda=\begin{pmatrix}
  \lambda·a_{1,1} & \lambda·a_{1,2} & \cdots & \lambda·a_{1,n} \\
  \lambda·a_{2,1} & \lambda·a_{2,2} & \cdots & \lambda·a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  \lambda·a_{m,1} & \lambda·a_{m,2} & \cdots & \lambda·a_{m,n} 
 \end{pmatrix}$$
   
Ejemplo:  
$$\begin{pmatrix}
  2 & 5 & 7 \\
  3 & 10 & 9 \\
  1 & 6 & 11\end{pmatrix}·2=\begin{pmatrix}
  4 & 10 & 14 \\
  6 & 20 & 18 \\
  2 & 12 & 22 \end{pmatrix}$$

In [2]:
import numpy as np
a = np.array([[2,5,7],[3,10,9],[1,6,11]])
print(a)
print('-----------')
print(2*a)

[[ 2  5  7]
 [ 3 10  9]
 [ 1  6 11]]
-----------
[[ 4 10 14]
 [ 6 20 18]
 [ 2 12 22]]


##### Producto punto por vector
$$\begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n} 
 \end{pmatrix}·\begin{pmatrix}
  b_{1,1} \\
  b_{2,1} \\
  \vdots \\
  b_{n,1}\end{pmatrix} =\begin{pmatrix}
  c_{1,1} \\
  c_{2,1} \\
  \vdots   \\
  c_{n,1} 
 \end{pmatrix}$$
 En donde cada $c_{ij}$:  
 $$c_{1,1}=a_{1,1}·b_{1,1}+a_{1,2}·b_{2,1}+\dotsb+a_{1,k}·b_{k,1}+\dotsb+a_{1,n}·b_{n,1}
 =\sum_{k=1}^n{a_{1,k}·b_{k,1}}$$
 $$c_{i,1}
 =\sum_{k=1}^n{a_{i,k}·b_{k,1}} \quad \quad \quad  i=1\dotsb n$$

   
Ejemplo:  
$$\begin{pmatrix}
  2 & 5 & 7 \\
  3 & 10 & 9 \\
  1 & 6 & 11\end{pmatrix}·\begin{pmatrix}
  5 \\
  1 \\
  2 \end{pmatrix}=\begin{pmatrix}
  29  \\
  43  \\
  33\end{pmatrix}$$  
  
Notar que el producto no es conmutativo:
    
$$\begin{pmatrix}
  5 & 1 & 2 \\
 \end{pmatrix}·\begin{pmatrix}
  2 & 5 & 7 \\
  3 & 10 & 9 \\
  1 & 6 & 11\end{pmatrix}=\begin{pmatrix}
  15 &47&66 \\
\end{pmatrix}$$

In [6]:
a = np.array([[2,5,7],[3,10,9],[1,6,11]])
b = np.array([5,1,2])
print(a)
print('-----------')
print(b)
print('-----------')
print(np.dot(a,b))
print(np.dot(b,a))

[[ 2  5  7]
 [ 3 10  9]
 [ 1  6 11]]
-----------
[5 1 2]
-----------
[29 43 33]
[15 47 66]


##### Producto punto de matrices
$$\begin{pmatrix}
  a_{1,1} & a_{1,2} & \cdots & a_{1,n} \\
  a_{2,1} & a_{2,2} & \cdots & a_{2,n} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  a_{m,1} & a_{m,2} & \cdots & a_{m,n} 
 \end{pmatrix}·\begin{pmatrix}
  b_{1,1} & b_{1,2} & \cdots & b_{1,w} \\
  b_{2,1} & b_{2,2} & \cdots & b_{2,w} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  b_{n,1} & b_{n,2} & \cdots & b_{n,w} 
 \end{pmatrix} =\begin{pmatrix}
  c_{1,1} & c_{1,2} & \cdots & c_{1,w} \\
  c_{2,1} & c_{2,2} & \cdots & c_{2,w} \\
  \vdots  & \vdots  & \ddots & \vdots  \\
  c_{n,1} & c_{n,2} & \cdots & c_{n,w} 
 \end{pmatrix}$$
 En donde cada $c_{ij}$:  
 $$c_{1,1}=a_{1,1}·b_{1,1}+a_{1,2}·b_{2,1}+\dotsb+a_{1,k}·b_{k,1}+\dotsb+a_{1,n}·b_{n,1}
 =\sum_{k=1}^n{a_{1,k}·b_{k,1}}$$
 $$c_{i,j}
 =\sum_{k=1}^n{a_{i,k}·b_{k,j}} \quad \quad \quad  i=1\dotsb n \quad \quad j=1\dotsb w$$  

   
Ejemplo:  
$$\begin{pmatrix}
  3 & 1  \\
  1 & 8 \\
  5 & 4 \end{pmatrix}·\begin{pmatrix}
  2 & 5 & 7 \\
  1 & 6 & 11\end{pmatrix}=\begin{pmatrix}
  7 & 21 & 32 \\
  10 & 53 & 95 \\
  14 & 49 & 79\end{pmatrix}$$  
  
Notar que el producto no es conmutativo:
    
$$\begin{pmatrix}
  2 & 5 & 7 \\
  1 & 6 & 11\end{pmatrix}·\begin{pmatrix}
  3 & 1  \\
  1 & 8 \\
  5 & 4 \end{pmatrix}=\begin{pmatrix}
  46 &70 \\
  64 &93 \\
\end{pmatrix}$$

In [10]:
a = np.array([[3,1],[1,8],[5,4]])
b = np.array([[2,5,7],[1,6,11]])
print(a)
print('-----------')
print(b)
print('-----------')
print(np.dot(a,b))
print(np.dot(b,a))

[[3 1]
 [1 8]
 [5 4]]
-----------
[[ 2  5  7]
 [ 1  6 11]]
-----------
[[ 7 21 32]
 [10 53 95]
 [14 49 79]]
[[46 70]
 [64 93]]


##### Algunas propiedades de las matrices
$$\lambda·(A+B)=\lambda·A+\lambda·B$$  
$$A+(B+C)=(A+B)+C$$  
$$A·(B+C)=A·B+A·C$$  
$$(A^T)^T=A$$
$$(A+B)^T=A^T+B^T$$
$$(A·B)^T=B^T·A^T$$
$$(B^T·A^T)^T=A·B$$