In [1]:
import numpy as np
from scipy.stats import mode
import pandas as pd

Estimadores.

In [2]:
numbers=np.arange(0,101,1)
numbers=np.append(numbers,np.array([25,25,50,45,30,25,25,25,30]))

media=np.mean(numbers)
mediana=np.median(numbers)
dev=np.std(numbers,ddof=1)
var=np.var(numbers,ddof=1)
# media=np.std(numbers)
# Para la moda en una variable continua se utiliza histograma con un n bin establecido
hist,bins=np.histogram(numbers,bins=10)
# Encuentra el índice del intervalo (bin) con la mayor frecuencia
indice_moda = np.argmax(hist)
# Imprime el rango del intervalo con la moda
print("Rango de la Moda:", (bins[indice_moda], bins[indice_moda + 1]))

print(f'media = {round(media,2)}   mediana = {round(mediana,2)}   desviacion estandar = {round(dev,2)}    varianza = {round(var,2)}')

Rango de la Moda: (20.0, 30.0)
media = 48.45   mediana = 46.5   desviacion estandar = 28.66    varianza = 821.44


Pandas.

Data Frames

In [3]:
datosLista = [[7, 6, 3], [10, 1, 4], [4, 2, 5], [12, 5, 11]]
datosArray = np.array([[7, 6, 3], [10, 1, 4], [4, 2, 5], [12, 5, 11]])
columnsNames=['col-1','col-2','col-3']
datosDicc=dict(zip(columnsNames,zip(*datosLista)))

print(f'Lista: {datosLista}')
print(f'Array: {datosArray}')
print(f'Diccionario: {datosDicc}')

# df=pd.DataFrame(datosLista,columns=columnsNames)
# df=pd.DataFrame(datosArray,columns=columnsNames)
df=pd.DataFrame(datosDicc)
df.head()


Lista: [[7, 6, 3], [10, 1, 4], [4, 2, 5], [12, 5, 11]]
Array: [[ 7  6  3]
 [10  1  4]
 [ 4  2  5]
 [12  5 11]]
Diccionario: {'col-1': (7, 10, 4, 12), 'col-2': (6, 1, 2, 5), 'col-3': (3, 4, 5, 11)}


col-1  col-2  col-3
0      7      6      3
1     10      1      4
2      4      2      5
3     12      5     11

Listar Columnas

In [4]:
list(df.columns)
df.columns.to_list()

['col-1', 'col-2', 'col-3']

Estimadores en pandas

In [5]:
df['col-1'].mean(), df['col-1'].median(),df['col-1'].std(),df['col-1'].var()

(8.25, 8.5, 3.5, 12.25)

In [6]:
pd.Series(numbers).mean(),pd.Series(numbers).median(),pd.Series(numbers).std(),pd.Series(numbers).var()

(48.45454545454545, 46.5, 28.66082464022185, 821.4428690575479)

Data Frame Manejo.

In [7]:
df.values

array([[ 7,  6,  3],
       [10,  1,  4],
       [ 4,  2,  5],
       [12,  5, 11]], dtype=int64)

In [8]:
# Devuelve un array bidimensional con la data es decir con todos los registros sin los nombres de columna.
df.values

array([[ 7,  6,  3],
       [10,  1,  4],
       [ 4,  2,  5],
       [12,  5, 11]], dtype=int64)

In [9]:
datosLista = [[7, 6, 3], [10, 1, 4], [4, 2, 5], [5, 5, 11],[5, 5, 11]]
df=pd.DataFrame(datosLista,columns=columnsNames)

In [10]:
# Cuenta registros IGUALES y ordena por la primera columna en form creciente por valor y primero por repeticion.
df.value_counts() 

col-1  col-2  col-3
5      5      11       2
4      2      5        1
7      6      3        1
10     1      4        1
Name: count, dtype: int64

Información del data frame.

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   col-1   5 non-null      int64
 1   col-2   5 non-null      int64
 2   col-3   5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes


In [12]:
df.describe()

col-1     col-2      col-3
count   5.000000  5.000000   5.000000
mean    6.200000  3.800000   6.800000
std     2.387467  2.167948   3.898718
min     4.000000  1.000000   3.000000
25%     5.000000  2.000000   4.000000
50%     5.000000  5.000000   5.000000
75%     7.000000  5.000000  11.000000
max    10.000000  6.000000  11.000000

Información personalizada.

In [13]:
info_df = pd.DataFrame(df.dtypes, columns=['Tipo de dato']) # df.dtypes devuelve una serie con los tipos de cada columna.
info_df['Valores no nulos'] = df.count()    # df.count() devuelve una serie con el conteo los valores no Nan de cada columna.
info_df['NaNs'] = df.isna().sum()   # df.isna().sum() primero identifica los NaNs y luego los suma por cada columna. Serie.
info_df['Valores únicos'] = df.nunique() # df.nunique() devuelve una serie con el conteo los valores únicos de cada columna. Serie
info_df['Valores cero'] = (df.eq(0)).sum() # df.eq(0).sum() devuelve una serie con el conteo los valores únicos de cada columna. Serie
info_df.T # Se transpone el dataframe creado (info_df)

col-1  col-2  col-3
Tipo de dato      int64  int64  int64
Valores no nulos      5      5      5
NaNs                  0      0      0
Valores únicos        4      4      4
Valores cero          0      0      0

Selecciones de columnas registros y rangos.

In [14]:
df['col-1'] # Esto devuelve una serie con la columna.
# type(df['col-1'])
df[['col-1']] # Esto devuelve un dataframe con la columna.
type(df[['col-1']])

pandas.core.frame.DataFrame

In [15]:
# loc[filas,[columnas]] devuelve un rango bidimensionl como otro dataframe. Los extremos si están incluidos.
df.loc[2:3,['col-1','col-2']]

col-1  col-2
2      4      2
3      5      5

In [29]:
# iloc[filas posicion,columnas posicion] devuelve un rango bidimensionl como otro dataframe. El extremo final NO están incluido.
# df.iloc[2:3,1:2]
df.iloc[2:3][['col-2']] # Otra forma de usar iloc combinando inices y nombres de columnas
# type(df.iloc[2,1:2]) # Cuando no se hace slice en filas o columnas o no se colocan [] devuelve una serie. Serie
# type(df.iloc[[2],1:2]) # dataframe.

col-2
2      2

Selección por condiciones.

In [17]:
condicion=df['col-1']>5
df[condicion]['col-2'] # Devuelve una serie.
df[condicion][['col-2']] # Devuelve un dataframe.


col-2
0      6
1      1

GroupBy. Agrupar por.

In [18]:
# Paso 1: Crear DataFrame

np.random.seed(0)
data = {
    "Tienda": ["Tienda1", "Tienda2", "Tienda1", "Tienda2", "Tienda1", "Tienda2"],
    "Producto": ["ProdA", "ProdA", "ProdA", "ProdB", "ProdB", "ProdB"],
    "CantidadVendida": np.random.randint(1, 10, 6),
    "PrecioUnitario": np.random.uniform(10, 50, 6),
}
dfv = pd.DataFrame(data)

# Paso 2: Agregar la columna "Venta"

dfv["Venta"] = dfv["CantidadVendida"] * dfv["PrecioUnitario"]
dfv

Tienda Producto  CantidadVendida  PrecioUnitario       Venta
0  Tienda1    ProdA                6       35.835765  215.014587
1  Tienda2    ProdA                1       27.503488   27.503488
2  Tienda1    ProdA                4       45.670920  182.683680
3  Tienda2    ProdB                4       48.546510  194.186042
4  Tienda1    ProdB                8       25.337661  202.701286
5  Tienda2    ProdB                4       41.669002  166.676006

Agrupar por Tienda.

In [19]:
type(dfv.groupby('Tienda')['Producto']) # Devuelve un tipo pandas.core.groupby.generic.SeriesGroupBy
# type(dfv.groupby('Tienda')['Producto'].nunique()) # Devuelve una serie
# pd.DataFrame(dfv.groupby('Tienda')['Producto'].unique()) # Se puede convertir en un dataframe.

pandas.core.groupby.generic.SeriesGroupBy

Cuando se agrupa se tiene que reducir por una función de agregación.  
Ejemplo: Encontrar el total de ventas por tienda.

In [22]:
dfv.groupby('Tienda')['Venta'].sum()    #Devuelve una serie
type(dfv.groupby('Tienda')['Venta'].sum())
dfv.groupby('Tienda')[['Venta']].sum()  # Devuelve un dataframe

Venta
Tienda             
Tienda1  600.399553
Tienda2  388.365536

Encontrar el producto más vendido por tienda.

In [37]:
imax=dfv.groupby('Tienda')['CantidadVendida'].idxmax()
dfv.iloc[imax,0:2]
# dfv.iloc[imax][['Tienda','Producto']] # Otra forma de usar iloc
imax

Tienda
Tienda1    4
Tienda2    3
Name: CantidadVendida, dtype: int64

Calcular el monto total de ventas por producto.

In [30]:
dfv.groupby('Producto')[['Venta']].sum()

Venta
Producto            
ProdA     425.201756
ProdB     563.563334

Encontrar la tienda con el mayor monto total de ventas.

In [42]:
imax=dfv.groupby('Tienda')[['Venta']].sum().idxmax()
imax.iloc[0]

'Tienda1'

Calcular el precio promedio de cada producto

In [45]:
dfv.groupby('Producto')[['PrecioUnitario']].mean()

PrecioUnitario
Producto                
ProdA          36.336724
ProdB          38.517724